### PR TITLE
update cs.po

### PR DESCRIPTION
**Pull request by warmsun0220**

### CODE REVIEW

**Comment by warmsun0220** [comment]
A friend sent the translation to me, and he said he try to communicate with language team at Zanata，but no respond. so I submint it as a commit. 
Thanks!

**Comment by gnome-mpv** [comment]
Is you friend Marek Suchánek by any chance? He seems to have already submitted the same translations to Zanata.

**Comment by warmsun0220** [comment]
Nope, he's name is ToMášMarný. I helped him upload translation before（long time ago). Maybe he also sent email to Marek Suchánek. 
If the translation will be update soon, just ignore this comment and close it. 
Thank you!

**Comment by gnome-mpv** [comment]
After looking more carefully, it seems that the translation in Zanata differs from this. The version in Zanata already covers everything in this commit though, so I'll just go ahead and close this pull request.

**Pull request closed without merging**
