### PR TITLE
msgmerge and half-done fix for #83

### PR DESCRIPTION
**Pull request by Arthur2e5**
I'm not sure about how translators of other languages normally deal with accel keys, and all I know is ja *kanjis* will not work just like these ones in zh…

Maybe I should try to learn about their behavior from l10n.gnome.org.

### CODE REVIEW

**Comment by gnome-mpv** [comment]
Merged as ebc0625 and a517a0b.

**Comment by Arthur2e5** [comment]
Ah…… Just out of curiosity, are you using things like `git pull --rebase=preserve my_repo thebranch` or just applying those patches provided by GitHub?

**Comment by gnome-mpv** [comment]
I just cherry-picked the commits.

**Comment by Arthur2e5** [comment]
I see.

**Pull request closed without merging**
