### PR TITLE
New zh_TW translations and zh_CN fixes.

### PR DESCRIPTION
**Pull request by Arthur2e5**
See comments under a133df1. You should really run `msgfmt -o /dev/null -vc --check-accelerator=_` foo.po before you accept changes…

There things are based on my zh_CN updates at #81, and they should work for zh_TW speakers.

I've aligned some terminology to their standards.

### CODE REVIEW

**Comment by warmsun0220** [comment]
Thank you for your corrections.  In fact, I just want to make chinese translations work. And now please take over this work. I will learn these documents. Thanks！

**Comment by Arthur2e5** [comment]
@warmsun0220 Sure, I will spare some of my power on this project. Don't be frustrated -- everyone makes mistakes. Just keep learning...

**Comment by TingPing** [comment]
On a side note wouldn't it be better to use an external tool such as http://zanata.org/ to manage translations rather than messy PRs?

**Comment by warmsun0220** [comment]
@Arthur2e5  Thanks, I will follow your suggestions.

**Comment by Arthur2e5** [comment]
@TingPing You're right, but for zanata… Well, I don't quite like it because of:
  * It's project grouping style. Rather than letting people explore a list sorted simply by names, transifex's tagging scheme makes translators feel better when exploring stuffs.
  * Some problems in its web frontend, for example:
    * This segment almost screwed up my Chrome running on Windows 10 en-US with a terrible flood of super thin SimSun glyphs. Luckily I have stylish and I can override it with even more `!important` directives.
    ```CSS
    .translationContainer pre, .translationContainer textarea {
        font-family: "Source Sans Pro","Helvetica Neue",blah,sans-serif !important;  /* ... */
    }
    ```
    * It's new alpha translation interface is a bit better (well, w/o `!important`), but with that `html lang=en` I still have to write some CSS.
    * Well, I've been waiting for the confirmation email from their bug tracker for 30 minutes.
  * Its team management style, and what happens with zh languages.
    * It may be better to provide the same team for every project for some potential benefits in consistency, but I'd rather limit the share-scope to some given groups of translations, preferably by the same developer(s) or in the same field.
    * I don't feel good seeing the same locale being split up like `zh-Hans-CN` & `zh-CN` (assuming we are not talking about pre-Hans PRC Chinese). Again, I'm waiting for their bug tracker confirmation mail.

**Comment by TingPing** [comment]
@Arthur2e5 As a project maintainer not translator I quite dislike both zanata and transifex, I just prefer the former because one or two features and the fact it is backed by fedora project.

**Comment by gnome-mpv** [comment]
Thanks. I'll look into zanata/transifex.

**Pull request merged**
