### PR TITLE
Initial Meson port

### PR DESCRIPTION
**Pull request by TingPing**
Translations commits from #261 are required so they are just included in the branch.

So rough usage:

Can install meson with `pip --user install meson` or your distro may be up to date.

```
meson build && cd build
ninja
```

It takes ~3 seconds to build on my machine (with `ccache`)

I know the `-Wconversion` gdbus `sed` hack wasn't ported over as I'd rather just fix that in upstream glib, though it can be replicated if needed.

### CODE REVIEW

**Comment by gnome-mpv** [comment]
>I know the -Wconversion gdbus sed hack wasn't ported over as I'd rather just fix that in upstream glib, though it can be replicated if needed.

Please add that to meson build as well. I find that it's easier to miss actual warnings with superfluous warnings around.

**Comment by TingPing** [comment]
Done.

**Comment by gnome-mpv** [comment]
Merged as 9f181b9f25c8a04f3a0f047bb91643e02c9fd766, d8fe8787a568b9107b46f9d1f3d6d34537aedaef, and d8fe8787a568b9107b46f9d1f3d6d34537aedaef.

**Comment by TingPing** [comment]
@gnome-mpv: btw: https://bugzilla.gnome.org/show_bug.cgi?id=778581

**Pull request closed without merging**
