### PR TITLE
Add loop button

### PR DESCRIPTION
**Pull request by gnarula**
Uses the loop property to allow looping the playlist infinitely.

### CODE REVIEW

**Comment by gnome-mpv** [comment]
I think it would be better to put the loop button in the playlist's context menu as a GtkCheckMenuItem to avoid cluttering the toolbar.

**Comment by TingPing** [comment]
Or a toolbar specific to the playlist pane.

**Comment by gnome-mpv** [comment]
>Or a toolbar specific to the playlist pane.

That's fine too, but I think it might be more visually appealing to keep the playlist toolbar-free.

**Comment by gnome-mpv** [comment]
bae1031

**Pull request closed without merging**
