### PR TITLE
Add Screenshot

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Comment by gnome-mpv** [comment]
Thank you, but I prefer not to put binary files in git repos since they tend to increase the size of the repo significantly. I'm also concerned about copyright issues since the video in the screenshot appears to be copyrighted.

**Comment by mmstick** [comment]
Copyright isn't a problem as this is covered under the **Fair Use Doctrine** which thereby permits usage without requiring permission.

**Comment by TingPing** [comment]
Or you could just use something you know you have rights to like Big Buck Bunny.

**Comment by gnome-mpv** [comment]
I have a few screenshots with Big Buck Bunny + Adwaita [on Github Pages](https://github.com/gnome-mpv/gnome-mpv.github.io). There are links to the screenshots in appdata.xml, so GNOME Software should be able to find them.

**Comment by mmstick** [comment]
You should link those screenshots in this repository then.

**Comment by gnome-mpv** [comment]
9c34d8925e9d2995e770547cc965fd625e063af7

**Comment by mmstick** [comment]
That's much better.

**Pull request closed without merging**
